#  ---------------------------------------------------------------------------
#
#  Description:  This file holds all my BASH configurations
#
#  ---------------------------------------------------------------------------

# Add `~/bin` to the `$PATH`
export PATH="$HOME/bin:$PATH";


for file in ~/.setup/shell/.{path,bash_prompt,exports,aliases,functions,extra}; do
	[ -r "$file" ] && [ -f "$file" ] && source "$file";
done;
unset file;

# RVM tools
source ~/.profile