#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Support 256 color
export TERM="xterm-256color"
export LANG="en_US.UTF-8"

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize Dark iTerm titlebar color (Source: https://codematters.blog/custom-iterm2-titlebar-background-colors-a088c6f2ec60)
echo -e '\033]6;1;bg;red;brightness;40\a'
echo -e '\033]6;1;bg;green;brightness;44\a'
echo -e '\033]6;1;bg;blue;brightness;52\a'

# why would you type 'cd dir' if you could just type 'dir'?
setopt AUTO_CD

# Now we can pipe to multiple outputs!
setopt MULTIOS

# This makes cd=pushd
setopt AUTO_PUSHD

# This will use named dirs when possible
setopt AUTO_NAME_DIRS

# If we have a glob this will expand it
setopt GLOB_COMPLETE
setopt PUSHD_MINUS

# No more annoying pushd messages...
# setopt PUSHD_SILENT

# blank pushd goes to home
setopt PUSHD_TO_HOME

# this will ignore multiple directories for the stack.  Useful?  I dunno.
setopt PUSHD_IGNORE_DUPS

# 10 second wait if you do something that will delete everything.  I wish I'd had this before...
setopt RM_STAR_WAIT

# use magic (this is default, but it can't hurt!)
setopt ZLE

setopt NO_HUP

setopt IGNORE_EOF

# If I could disable Ctrl-s completely I would!
setopt NO_FLOW_CONTROL

# Keep echo "station" > station from clobbering station
setopt NO_CLOBBER

# Case insensitive globbing
setopt NO_CASE_GLOB

# Be Reasonable!
setopt NUMERIC_GLOB_SORT

# I don't know why I never set this before.
setopt EXTENDED_GLOB

# hows about arrays be awesome?  (that is, frew${cool}frew has frew surrounding all the variables, not just first and last
setopt RC_EXPAND_PARAM

# Who doesn't want home and end to work?
bindkey '\e[1~' beginning-of-line
bindkey '\e[4~' end-of-line

# Incremental search is elite!
bindkey -M vicmd "/" history-incremental-search-backward
bindkey -M vicmd "?" history-incremental-search-forward

# Search based on what you typed in already
bindkey -M vicmd "//" history-beginning-search-backward
bindkey -M vicmd "??" history-beginning-search-forward

bindkey "\eOP" run-help

# oh wow!  This is killer...  try it!
bindkey -M vicmd "q" push-line

# it's like, space AND completion.  Gnarlbot.
bindkey -M viins ' ' magic-space

#   -----------------------------
#   EXPORTS
#   -----------------------------
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh" # This loads nvm
export PATH="$PATH:$HOME/.rvm/bin" # Add RVM to PATH for scripting
test -e "${HOME}/.iterm2_shell_integration.zsh" && source "${HOME}/.iterm2_shell_integration.zsh"

export MonkeyDevPath=/opt/MonkeyDev
export MonkeyDevDeviceIP=
export PATH=/opt/MonkeyDev/bin:$PATH
export PATH="/usr/local/opt/gnu-tar/libexec/gnubin:$PATH" 
export THEOS="/opt/theos"

#   -----------------------------
#   MAKE TERMINAL BETTER
#   -----------------------------

alias which='type -a'                     	# which:        Find executables
alias path='echo -e ${PATH//:/\\n}'         # path:         Echo all executable Paths
alias please='sudo $(fc -ln -1)'            # Rerun previous command under sudo

#   -------------------------------
#   DIRECTORY SHORTCUTS
#   -------------------------------

alias gt_project="cd ~/Documents/Projects"
alias gt_download="cd ~/Downloads"

#   ---------------------------------------
#   DEVELOPMENT
#   ---------------------------------------

#   REACT NATIVE
alias reactcli="npm install -g react-native-cli"
alias reactios="react-native run-ios"
alias reactintegrate="(JS_DIR=`pwd`/ReactComponent; cd node_modules/react-native; npm run start -- --root `pwd`/ReactComponent)"

#   ---------------------------------------
#   OTHER TOOLS
#   ---------------------------------------

# Thefuck (https://github.com/nvbn/thefuck)
eval "$(thefuck --alias)"
# You can use whatever you want as an alias, like for Mondays:
eval "$(thefuck --alias FUCK)"

# Gitignore (https://www.gitignore.io)
function gi() { curl -L -s https://www.gitignore.io/api/$@ ;}

# z: jumping between projects (https://github.com/rupa/z)
# Tracks your most used directories, based on 'frecency'.
. `brew --prefix`/etc/profile.d/z.sh
